# Build settings
markdown : kramdown
permalink: pretty

# Site settings
url        : "http://aaron.codes"
title      : aaron.codes
email      : hire@aaron.codes
description: >
  I'm a talented back-to-front-end web developer, based in the UK. I've got a great deal to offer and I'm extremely passionate about our work.
  Get in touch and we'll build something beautiful.

gplus_username: +aaronlords
twitter_username: _aaronlord
github_username :  aaronlord

adam_dribbble_username: kralcmada

coding_since: 2007;
